### ISSUE TITLE
[FEATURE] Enhance workflow trigger to create and update check runs

### ISSUE THREAD

**Issue by guibranco** [guibranco/gstraccini-bot-service#887]
Currently, when the bot detects a workflow comment in a pull request, it triggers a workflow dispatch in a dedicated repository. The workflow runs and posts a result comment back in the target pull request.

We want to enhance this process by integrating **GitHub Checks** to better reflect the status (queued, in progress, success, failure, etc.) of the workflow execution.

The new flow should be:
- When the bot detects a workflow comment:
  - It **creates a check run** in the target repository with the initial state `queued` (instead of `in_progress`).
  - It **dispatches the workflow** and passes the **Check Run ID** as a parameter.
- In the workflow:
  - Update the check run status to **in_progress** once the job starts.
  - Update the check run conclusion to **success**, **failure**, **cancelled**, or **timed_out** based on the job result.

This improvement will make the GitHub UI show the running and completed checks properly, giving users clearer feedback without needing to rely only on comments.

## Sample implementation code
**Trigger workflow (PHP):** (comments.php)
```php
function callWorkflow($config, $metadata, $comment, $workflow, $extendedParameters = null): void
{
    $pullRequestResponse = doRequestGitHub($metadata["token"], $metadata["pullRequestUrl"], null, "GET");
    $pullRequest = json_decode($pullRequestResponse->getBody());

    $tokenBot = generateInstallationToken($config->botRepositoryInstallationId, $config->botRepository);
    $url = "repos/" . $config->botWorkflowsRepository . "/actions/workflows/" . $workflow . "/dispatches";

    // Create the Check Run first (new step!)
    $checkRunId = setCheckRunQueued($metadata, $pullRequest->head->sha, "Workflow");

    $data = array(
        "ref" => "main",
        "inputs" => array(
            "owner" => $comment->RepositoryOwner,
            "repository" => $comment->RepositoryName,
            "branch" => $pullRequest->head->ref,
            "pull_request" => $comment->PullRequestNumber,
            "installationId" => $comment->InstallationId,
            "check_run_id" => $checkRunId // 🚀 Pass the Check Run ID
        )
    );
    if ($extendedParameters !== null) {
        $data["inputs"] = array_merge($data["inputs"], $extendedParameters);
    }
    doRequestGitHub($tokenBot, $url, $data, "POST");
}
```

**Create check run (PHP):** (github.php)
```php
function setCheckRunQueued(array $metadata, string $commitId, string $type): int
{
    $checkRunBody = array(
        "name" => constant("BOT_CHECK_MESSAGE_PREFIX") . ucwords($type),
        "details_url" => $metadata["dashboardUrl"],
        "head_sha" => $commitId,
        "status" => "queued",
        "output" => array(
            "title" => "Checks queued 🕓",
            "summary" => "GStraccini is preparing to check this " . strtolower($type) . "!",
            "text" => ""
        )
    );

    $response = doRequestGitHub($metadata["token"], $metadata["checkRunUrl"], $checkRunBody, "POST");
    $result = json_decode($response->getBody());
    return $result->id;
}
```

**Sample workflow (YAML):** (code in guibranco/gstraccini-bot-workflows repository)
```yaml
name: NPM Dist

on:
  workflow_dispatch:
    inputs:
      owner:
        description: "The owner of the repository to run"
        required: true
      repository:
        description: "The repository to run"
        required: true
      branch:
        description: "The branch to run"
        required: true
      pull_request:
        description: "The pull request number"
        required: true
      installationId:
        description: "The installation id"
        required: true
      check_run_id:
        description: "The check run id"
        required: true

permissions:
  contents: read
  pull-requests: write
  checks: write

env:
  GHA_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ github.event.inputs.installationId }}

      - name: Mark check run as in_progress
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          check_id: ${{ github.event.inputs.check_run_id }}
          status: in_progress
          details_url: ${{ env.GHA_URL }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: "${{ github.event.inputs.owner}}/${{ github.event.inputs.repository }}"
          ref: ${{ github.event.inputs.branch }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22.x

      - name: Install & Test
        run: npm install

      - name: Run NPM package
        run: npm run package

      - name: Update PR with comment (success)
        if: success()
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          repo-owner: ${{ github.event.inputs.owner }}
          repo-name: ${{ github.event.inputs.repository }}
          issue: ${{ github.event.inputs.pull_request }}
          refresh-message-position: true
          allow-repeats: true
          message: |
            :white_check_mark: [NPM Dist](${{ env.GHA_URL }}) executed successfully!

      - name: Mark check run as success
        if: success()
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          check_id: ${{ github.event.inputs.check_run_id }}
          conclusion: success
          details_url: ${{ env.GHA_URL }}
          output: |
            {"title": "Workflow passed ✅", "summary": "See details in the workflow run."}

      - name: Update PR with comment (failure)
        if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          repo-owner: ${{ github.event.inputs.owner }}
          repo-name: ${{ github.event.inputs.repository }}
          issue: ${{ github.event.inputs.pull_request }}
          refresh-message-position: true
          allow-repeats: true
          message: |
            :x: [NPM Dist](${{ env.GHA_URL }}) failed!

      - name: Mark check run as failure
        if: failure()
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          check_id: ${{ github.event.inputs.check_run_id }}
          conclusion: failure
          details_url: ${{ env.GHA_URL }}
          output: |
            {"title": "Workflow failed ❌", "summary": "See details in the workflow run."}

```

## What needs to be done
- [x] Modify `setCheckRunInProgress()` to allow creating a check run with `"status": "queued"`.
- [x] Pass the `check_run_id` as a new input when dispatching the workflow.
- [x] Update all workflows to accept the `check_run_id` input.
- [ ] Create reusable steps (or actions) in the workflows:
  - To set the check run status to `in_progress` at the start.
  - To set the check run conclusion (`success`, `failure`, `cancelled`, etc.) at the end.
- [x] Update the bot to send API requests to update the check run status accordingly.

## Acceptance Criteria
- [x] When a workflow is triggered, a corresponding check run is created in `queued` status.
- [x] Workflow should update the check run to `in_progress` when execution starts.
- [x] Workflow should update the check run to `success`, `failure`, or other appropriate conclusions when finished.
- [x] If the workflow fails to start or is cancelled, the check run must reflect this properly.
- [x] Final comments in the PR should still be posted (no changes to the user-facing messages).
